USE MASTER
GO
IF DB_ID('EXAMEN_POO_2') IS NOT NULL
	BEGIN
		DROP DATABASE EXAMEN_POO_2
	END
GO
CREATE DATABASE EXAMEN_POO_2
GO
USE EXAMEN_POO_2
GO
CREATE TABLE EMPLEADO(
IDEMPLEADO INT PRIMARY KEY IDENTITY,
NOMBRE VARCHAR(50) NOT NULL,
CEDULA VARCHAR(10) UNIQUE NOT NULL,
DIRECCION VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(10) UNIQUE NOT NULL,
SUELDO REAL NOT NULL,
FECHA_INGRESO DATE NOT NULL,
CARGO VARCHAR(50) UNIQUE NOT NULL
)
GO
CREATE PROCEDURE INSERTAR_EMPLEADO
@NOMBRE VARCHAR(50), @CEDULA VARCHAR(10), @DIRECCION VARCHAR(50), @TELEFONO VARCHAR(10), @SUELDO REAL, @FECHA_INGRESO DATE, @CARGO VARCHAR(50)
AS
INSERT EMPLEADO(NOMBRE, CEDULA, DIRECCION, TELEFONO, SUELDO, FECHA_INGRESO, CARGO)
		VALUES(@NOMBRE, @CEDULA, @DIRECCION, @TELEFONO, @SUELDO, @FECHA_INGRESO, @CARGO)
GO
CREATE PROCEDURE MODIFICAR_EMPLEADO
@IDEMPLEADO INT, @NOMBRE VARCHAR(50), @CEDULA VARCHAR(10), @DIRECCION VARCHAR(50), @TELEFONO VARCHAR(10), @SUELDO REAL, @FECHA_INGRESO DATE, @CARGO VARCHAR(50)
AS
UPDATE [DBO].[EMPLEADO]
	SET [NOMBRE] = @NOMBRE,
		[CEDULA] = @CEDULA,
		[DIRECCION] = @DIRECCION,
		[TELEFONO] = @TELEFONO,
		[SUELDO] = @SUELDO,
		[FECHA_INGRESO] = @FECHA_INGRESO,
		[CARGO] = @CARGO
WHERE [IDEMPLEADO] = @IDEMPLEADO
GO
CREATE PROCEDURE ELIMINAR_EMPLEADO
@IDEMPLEADO INT
AS
DELETE EMPLEADO WHERE IDEMPLEADO = @IDEMPLEADO
GO
CREATE PROCEDURE CONSULTAR_EMPLEADO
@NOMBRE VARCHAR(50)
AS
SELECT * FROM EMPLEADO WHERE [NOMBRE] LIKE '%'+@NOMBRE+'%'
GO
EXECUTE INSERTAR_EMPLEADO 'JOSE FARIAS', '0958986804', 'LA PRADERA GRUPO 4', '0968229582', 400, '1-8-2020', 'GERENTE'
GO
EXECUTE CONSULTAR_EMPLEADO ''
GO